/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cesar' at '11/9/15 3:51 PM' with Gradle 2.6
 *
 * @author cesar, @date 11/9/15 3:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
